
import type { Metadata, Viewport } from "next";
import { SN_Pro } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import { Providers } from "@/components/Providers";

const SNPro = SN_Pro({
  variable: "--font-sn-pro",
  subsets: ["cyrillic", "latin"],
  weight: ["200", "300", "400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'luxf.light',
    startupImage: [
      { url: '/splash/iphone-15-pro.png', media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3)' },
      // + варианты под другие размеры экранов
    ],
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${SNPro.variable} h-full antialiased`}
    >
      <Providers>
        <Layout>
          {children}
        </Layout>
      </Providers>
    </html>
  );
}
