
import type { Metadata } from "next";
import { SN_Pro } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import { Providers } from "@/components/Providers";

const SNPro = SN_Pro({
  variable: "--font-sn-pro",
  subsets: ["cyrillic", "latin"],
  weight: ["200", "300", "400", "500", "600", "700"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ru"
      className={`${SNPro.variable} h-full antialiased`}
    >
      <Providers>
        <Layout>
          {children}
        </Layout>
      </Providers>
    </html>
  );
}
